name: Bug Report (forms based)
description: File a bug report
labels: [bug]
body:
- type: textarea
  id: Description
  attributes:
    label:  Describe the bug
    description: "A clear and concise description of the bug"
  validations:
    required: true
- type: textarea
  id: RepoSteps
  attributes:
    label:  Repo Steps
    description: "Steps to reproduce the behavior"
    value: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
      ...
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label:  Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  id: extraInfo
  attributes:
    label:  Logging Information
    description: |
      - Please provide debug logs of the problem
      - If applicable, add screenshots to help explain your problem.
  validations:
    required: false
